jenkinsci/crowd2-plugin

- src/main/java/de/theit/jenkins/crowd/CrowdConfigurationService.java
Issue link [https://issues.jenkins-ci.org/browse/JENKINS-40472](https://issues.jenkins-ci.org/browse/JENKINS-40472)
> JENKINS-40472 allow blanks in parameter 'Restrict groups'

- pom.xml
set jenkins.version to past lts release
> Support past LTS release

- Jenkinsfile
- pom.xml
- src/test/java/de/theit/jenkins/crowd/CrowdMailAddressResolverImplTest.java
- src/test/java/de/theit/jenkins/crowd/CrowdUserDetailsServiceTest.java
- src/test/java/de/theit/jenkins/crowd/CrowdUserTest.java
- Sadly, this won't be possible as I don't have admin access to this repository and because of that, the `Jenkinsfile` I'm submitting will not be picked by ci.jenkins.io.
> [JENKINS-59301] Update plugin build process

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
- src/main/java/de/theit/jenkins/crowd/CrowdConfigurationService.java
- src/main/java/de/theit/jenkins/crowd/CrowdSecurityRealm.java
First attempt to modernize plugin.
Changes:
* Jenkins core bump to 2.277. I picked 2.277 as a base mostly, because It should be upgraded gradually. I think that starting from 1y old core will be good beginning, and this change can reach most of current users. 
* parent pom bump to 4.39 (latest version)
* added incremental releases so users can help me with debugging and development
* added spotbugs so I can better determine PR quality
* updated connect url
> Update core to 2.277 and parent pom

- .github/dependabot.yml
> Add github action for updating dependencies

- .github/release-drafter.yml
Adding release drafter which will help me preparing changelog. 
This changelog will be prepared in fly during the development process.
> Add release drafter github action

- .github/workflows/jenkins-security-scan.yml
Add usage of new graphql.
https://www.jenkins.io/doc/developer/security/scan/
> Add security scan workflow

- pom.xml
Adding billing materials improve releases by automating dependencies.
> Add billing materials

- src/main/java/de/theit/jenkins/crowd/CrowdSecurityRealm.java
Fix missing POST decorators form forms functions.
This errors was reported by Graphql.
> Add post to public form functions

- src/main/java/de/theit/jenkins/crowd/CrowdConfigurationService.java
Refactor duplicated code to reduce number of changes in feature code changes
> Refactor duplicated code for cache operation

- docs/Modernisation.md
- pom.xml
- src/main/java/de/theit/jenkins/crowd/CrowdServletFilter.java
Add findsecbugs to pom.xml, and fix reported issues.
> [Feature] Enable findsecbugs plugin from spotbugs

- .github/sonar-scan.yml
- pom.xml
I find a sonar scans quite useful so this will provide an integration with it. Sadly this is an open source project so without founding pr checks are disabled.
More here:
https://docs.sonarqube.org/latest/analysis/github-integration/
https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-maven/
> Add sonar qube scans

- .github/workflows/sonar-scan.yml
- src/main/java/de/theit/jenkins/crowd/CrowdAuthenticationToken.java
- src/main/java/de/theit/jenkins/crowd/CrowdConfigurationService.java
- src/test/java/de/theit/jenkins/crowd/CrowdMailAddressResolverImplTest.java
- src/test/java/de/theit/jenkins/crowd/CrowdUserTest.java
Remove sonarqube reported code smells
> [Bugfix] Remove code smells

- src/main/java/de/theit/jenkins/crowd/CrowdConfigurationService.java
Refactor code to be more simple by reduce Cognitive Complexity.
This code was duplicated and it was different in only one line.
I changed level of if statement and make use of common logic.
https://sonarcloud.io/organizations/jenkins-crowd2-plugin/rules?open=java%3AS3776&rule_key=java%3AS3776
> Remove duplicated code for getting user groups

- src/main/java/de/theit/jenkins/crowd/CrowdAuthenticationManager.java
- src/main/java/de/theit/jenkins/crowd/CrowdConfigurationService.java
- src/main/java/de/theit/jenkins/crowd/CrowdMailAddressResolverImpl.java
- src/main/java/de/theit/jenkins/crowd/CrowdRememberMeServices.java
- src/main/java/de/theit/jenkins/crowd/CrowdSecurityRealm.java
- src/main/java/de/theit/jenkins/crowd/CrowdServletFilter.java
- src/main/java/de/theit/jenkins/crowd/CrowdUserDetailsService.java
Use more consistent way of logging.
> Use consistient way of logging

- .github/workflows/release-drafter.yml
> chore: enable release drafter

- .github/workflows/crowdin.yml
> chore: update crowding gh action

- .github/workflows/sonar-scan.yml
> chore: update gh actions for sonar

- _init.sh
- _release.sh
- pom.xml
> fix: ci builds

- .github/workflows/crowdin.yml
- .github/workflows/sonar-scan.yml
> chore: update GH

- README.md
Update readme documentation for crowd2 after recent release.
> docs: update used versions and fix urls

- pom.xml
Update Jenkins bom to 1654.vcb_69d035fa_20
> deps: update bom to 1654.vcb_69d035fa_20

- .github/dependabot.yml
Try and stop dependabot pr's for incremental versions.
> cicd: Dependabot update

- pom.xml
> chore: remove duplicated dependency

- pom.xml
> deps: update jenkins core to 2.361.4

- .gitpod.yml
- CONTRIBUTING.md
- README.md
- _clear.sh
- _init.sh
- _start.sh
- casc/Dockerfile
- casc/docker-compose.yml
- pom.xml
Update the dev environment to follow the current repo setup.
> chore: update development environment

- README.md
> docs: update crowd version

- casc/Dockerfile
See: https://github.com/jenkinsci/crowd2-plugin/pull/169#issuecomment-1584371090
> Override plugin in ref folder on update

- pom.xml
> deps: update crow rest client to 5.1.3
